kind: ConfigMap
metadata:
  name: {{ include "inji-web.fullname" . }}
apiVersion: v1
data:
  default.conf: |
    server {
        listen 80;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }


        location /v1/mimoto/ {
            proxy_pass http://mimoto.mimoto.svc.cluster.local:8089/residentmobileapp/;
        }


        error_page   500 502 503 504  /50x.html;

        location = /50x.html {
        root   /usr/share/nginx/html;
        }
    }
