apiVersion: v2
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: A Helm chart for MOSIP Softhsm module
home: https://mosip.io
keywords:
- softhsm
- hsm
maintainers:
- email: info@mosip.io
  name: MOSIP
name: softhsm
type: application
version: 12.0.1
