apiVersion: v2
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: A Helm chart for MOSIP esignet module
home: https://mosip.io
keywords:
- mosip
- esignet
maintainers:
- email: info@mosip.io
  name: MOSIP
name: esignet
type: application
version: 1.4.0
